### PR TITLE
feat: to select table directly in the sidebar

### PR DESCRIPTION
**Pull request by CorrectRoadH**
- [x] Style
- [x] ~~A better selected Tables state manage~~ (Something needs to be refactor something here. I think it would be better to put it in the next PR.)
- [x] Implement Schema for PostgreSQL. I will implement it in #112
- [x] Performance optimize
- [x] ~~Better Code Struct~~ 🤔 `src/components/ConnectionSidebar.tsx` has too long code. I think it is good to extract some code to new components. But I think it is a big change. might be hard to review. So I want to do it in another PR.

CleanShot 2023-05-31 at 09 47 46

wait for #112 to be merged

What does the PR do?
- a new component: checkbox
- refactor multiple select as checkbox
- ~~refactor selected state. move selectedTablesName from conversationStore to TableList. Because add a schema. (WIP)~~

### CODE REVIEW

**Review by tianzhou — COMMENTED** [review]
This is still marked as WIP, is this ready for review

**Comment by CorrectRoadH** [comment]
> This is still marked as WIP, is this ready for review

#112 is ready for review. The PR dep #112. 👀 I think #112 should be reviewed and merged. But The PR has some work need to do. It may be completed today.

**Review by tianzhou — COMMENTED** [review]
I have merged #112 , please sync with head and I will continue review.

**Comment by CorrectRoadH** [comment]
> I have merged #112 , please sync with head and I will continue review.

PTAL

**Review by tianzhou — APPROVED** [review]
LGTM

**Comment by tianzhou** [comment]
Thanks for implementing this, it will definitely be a good addition to the product.

**Pull request merged**
